labguage: node_js

sudo: required

before_script:
  - npm cache clean -f
  - npm i -g npm@next
  - sudo npm install -g n
  - sudo n stable
  - node -v
  - npm -v
  - npm i -g mocha
  - npm i

script:
  - npm test
