export const RESET_PRICE_VIEW_IN_NEW = 'RESET_PRICE_VIEW_IN_NEW';

export const MAKE_INPUT_IN_NEW = 'MAKE_INPUT_IN_NEW';
export const REMOVE_INPUT_IN_NEW = 'REMOVE_INPUT_IN_NEW';

export const CHANGE_PRODUCT_FIELD_IN_NEW = 'CHANGE_PRODUCT_FIELD_IN_NEW';
export const CHANGE_MAIN_FIELD_IN_NEW = 'CHANGE_MAIN_FIELD_IN_NEW';
export const INPUT_INSERT_ERROR_IN_NEW = 'INPUT_INSERT_ERROR_IN_NEW';

export const CREATE_NEW_PRODUCT_IN_NEW = 'CREATE_NEW_PRODUCT_IN_NEW';
export const REMOVE_NEW_PRODUCT_IN_NEW = 'REMOVE_NEW_PRODUCT_IN_NEW';

export const CREATING_LOADING = 'CREATING_LOADING';
export const PRICE_CREATING_ERROR = 'PRICE_CREATING_ERROR';
export const PRICE_CREATING_SUCCESS = 'PRICE_CREATING_SUCCESS';

export const SET_COUNTERS_IN_NEW = 'SET_COUNTERS_IN_NEW';
export const SHOW_LINK_TO_LOGIN = 'SHOW_LINK_TO_LOGIN';
