export const IS_VALUE_UNIQUE = 'IS_VALUE_UNIQUE';
export const UNIQUENESS_ERROR = 'UNIQUENESS_ERROR';

export const CHECKING_LOADING_IN_CUSTOMER_FIELD = 'CHECKING_LOADING_IN_CUSTOMER_FIELD';

export const CHANGE_FILED_AS_CUSTOMER = 'CHANGE_FILED_AS_CUSTOMER';
export const VALIDATION_ERROR = 'VALIDATION_ERROR_AS_CUSTOMER'
export const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS_AS_CUSTOMER';

export const fieldsIds = {
  username: 'usernameAsCustomer',
  email: 'customerEmail',
  password: 'customerPassword'
};

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const REGISTERED = 'REGISTERED';