export const CHANGE_LOGIN_FORM_FIELD = "CHANGE_LOGIN_FORM_FIELD";

export const LOGINING_LOADING = "LOGINING_LOADING";
export const LOGINING_ERROR = "LOGINING_ERROR";
export const LOGIN = "LOGIN";

export const TO_REGISTER = "TO_REGISTER";

export const INPUT_VALIDATION_ERROR = "INPUT_VALIDATION_ERROR";
export const RESET_VALIDATION_ERRORS = "RESET_VALIDATION_ERRORS";